version: 1.0.{build}-{branch}

build: off

artifacts:
  - path: build\**\*.tar.gz
    name: joi-array-extensions

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

matrix:
  fast_finish: true

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm config set progress false
  - npm config set spin false
  - npm install

test_script:
  - npm test